### ISSUE TITLE
Tweaks Suggestions

### ISSUE THREAD

**Issue by tapchik** [tapchik/Train-Nums#1]
**Here you can leave your suggestions for tweaks and changes for Train Nums code.** 

@QuantumNovice

**Comment by QuantumNovice** [comment]
https://github.com/tapchik/Train-Nums/blob/f076752331f707174baac768b79ac431727a23e7/TrNu-1.3.py#L10-L18
When using `'''` or `"""` you don't need to add `\` to indicate the string continues in next line.
Use `\` for strings that start with `'` or `"`.

**Comment by QuantumNovice** [comment]
Instead of using these
https://github.com/tapchik/Train-Nums/blob/f076752331f707174baac768b79ac431727a23e7/TrNu-1.3.py#L21
https://github.com/tapchik/Train-Nums/blob/f076752331f707174baac768b79ac431727a23e7/TrNu-1.3.py#L29
use 
```python
with open("TrNuSettings.txt", "r") as blok:
   # Statements here
```
File is closed automatically.

**Comment by QuantumNovice** [comment]
No need for parenthesis here.
https://github.com/tapchik/Train-Nums/blob/f076752331f707174baac768b79ac431727a23e7/TrNu-1.3.py#L22

**Comment by QuantumNovice** [comment]
This is a bit slower.
https://github.com/tapchik/Train-Nums/blob/f076752331f707174baac768b79ac431727a23e7/TrNu-1.3.py#L48-L51

```
blok.write('1\n
        0\n
        25\n
        1')
```

**Comment by QuantumNovice** [comment]
I have notices you're using a lot of these
https://github.com/tapchik/Train-Nums/blob/f076752331f707174baac768b79ac431727a23e7/TrNu-1.3.py#L53-L56
This isn't necessary. If you want to specify type of object. Python has optional static typing
do this.
```python
x : int = 1
y : float = 0.1
name : str = "Hello"
data : list = [1, 2, 3]
```

**Comment by tapchik** [comment]
> This isn't necessary. If you want to specify type of object. Python has optional static typing
> do this.
> 
> ```python
> x : int = 1
> y : float = 0.1
> name : str = "Hello"
> data : list = [1, 2, 3]
> ```

So does `x : int = 5` equals `x = int(5)`?

**Comment by QuantumNovice** [comment]
`x : int  = 5` is equivalent to `int x = 5` in C or C++.
In python you don't need to specify the type of data. Python already knows 
that 5 is an `int`.
No 5 is already an int. 
```python
>>> type(5)
<class 'int'>
>>> type ( int(5) )
<class 'int'>
```

**Comment by QuantumNovice** [comment]
To make code readable don't use too much paranthesis `(`, `)`
https://github.com/tapchik/Train-Nums/blob/d146d3c6c888463d875849e7eeebf6243d26b993/TrNu-1.3.py#L186

**Comment by QuantumNovice** [comment]
These variable names are killing me.
https://github.com/tapchik/Train-Nums/blob/d146d3c6c888463d875849e7eeebf6243d26b993/TrNu-1.3.py#L5
https://github.com/tapchik/Train-Nums/blob/d146d3c6c888463d875849e7eeebf6243d26b993/TrNu-1.3.py#L22
https://github.com/tapchik/Train-Nums/blob/d146d3c6c888463d875849e7eeebf6243d26b993/TrNu-1.3.py#L23

**Comment by QuantumNovice** [comment]
https://github.com/tapchik/Train-Nums/blob/be6d14c03bd2b21ba04cfad293a28b229294777a/TrNu-1.3.py#L36
Instead write `abs(x)` as it'll crash for negative numbers.

**Comment by QuantumNovice** [comment]
Spaces between functions name and it's arguments should be avoided.
https://github.com/tapchik/Train-Nums/blob/be6d14c03bd2b21ba04cfad293a28b229294777a/TrNu-1.3.py#L32

**Comment by QuantumNovice** [comment]
Use consistent indentation that are a multiple of four.
https://github.com/tapchik/Train-Nums/blob/be6d14c03bd2b21ba04cfad293a28b229294777a/TrNu-1.3.py#L36

**Comment by tapchik** [comment]
> Use consistent indentation that are a multiple of four.
@QuantumNovice what?

**Comment by tapchik** [comment]
@QuantumNovice wait, I got it. I was switching between two IDE, and one of them was a little broken. I will fix that.

**Comment by QuantumNovice** [comment]
> 
> 
> Spaces between functions name and it's arguments should be avoided.
> 
> https://github.com/tapchik/Train-Nums/blob/be6d14c03bd2b21ba04cfad293a28b229294777a/TrNu-1.3.py#L32

Python has a syntax conventions called PEP while everything is allowed in python but to make code
more readable Python-programmer follows PEP guidelines.

**Comment by QuantumNovice** [comment]
Here use `is` instead of `==` as both the statements are identical but the later makes it more readable.

**Comment by QuantumNovice** [comment]
https://github.com/tapchik/Train-Nums/blob/be6d14c03bd2b21ba04cfad293a28b229294777a/TrNu-1.3.py#L84-L87
https://github.com/tapchik/Train-Nums/blob/be6d14c03bd2b21ba04cfad293a28b229294777a/TrNu-1.3.py#L122-L125
Unnecessary else
```
  if options != []:
    return choice(options)
  return None
```

**Comment by tapchik** [comment]
@QuantumNovice Is `print ("Hi")` ok or whould I write `print("Hi!")`?

**Comment by QuantumNovice** [comment]
https://github.com/tapchik/Train-Nums/blob/be6d14c03bd2b21ba04cfad293a28b229294777a/TrNu-1.3.py#L15 
`quit` is a builtin function. Avoid using builtin functions.

**Comment by QuantumNovice** [comment]
> 
> 
> @QuantumNovice Is `print ("Hi")` ok or whould I write `print("Hi!")`?

For now it's ok for now. Try to avoid it in future coding.

**Comment by QuantumNovice** [comment]
https://github.com/tapchik/Train-Nums/blob/be6d14c03bd2b21ba04cfad293a28b229294777a/TrNu-1.3.py#L1-L2
```python
from random import randint
from random import choice
```
